FROM node:12 as build

WORKDIR /app

COPY ./loginApp/package*.json ./

RUN npm install

COPY . .

# ENV PORT=3001

# EXPOSE 3001

RUN npm run build

FROM nginx:1.21.5-alpine as prod

COPY --from=build /app/dist /usr/share/nginx/html

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]