pipeline {
    agent any 

    tools {nodejs "npm"}
    
    environment {
      
        registry = "mojdockerbre/auth:auth-loginapp-v1-prod"
        registryCredential = 'auth-app-tokencina'
        dockerImage = ''
    }
    
    stages {
     stage('Cloning Git') {
           steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'loginApp']], userRemoteConfigs: [[url: 'https://github.com/alexomon018/auth']]])       
            }
        }
    
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build("auth:auth-loginapp-v1-prod", "--platform=linux/amd64 -f ./loginApp/Dockerfile.prod .") registry
        }
      }
    }
    
    
    stage('Upload Image') {
     steps{    
         script {
            docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            }
        }
      }
    }
  }
}