pipeline {
    agent any 

    tools {nodejs "npm"}
    
    environment {
      
        registry = "mojdockerbre/auth:auth-loginapp-v1-prod"
     
        registryCredential = 'auth-app-tokencina'
        dockerImage = ''
    }
    
    stages {
        stage('Cloning Git') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/alexomon018/auth']]])       
            }
        }
    
    stage('Building image') {
      steps{
        script {
          // dockerImage = docker.build("auth:auth-loginapp-v1-prod","-f ./loginApp/Dockerfile.prod .") registry
          sh "docker buildx build -f Dockerfile.prod --platform=linux/amd64  -t  mojdockerbre/auth:auth-loginapp-v1-prod ."
        }
      }
    }
    
    
    stage('Upload Image') {
     steps{    
         script {
            docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            }
        }
      }
    }
  }
}