pipeline {
    agent any 
    
    environment {
        registry = "mojdockerbre/auth:auth-loginapp-v1-prod"
        registryCredential = 'auth-app-tokencina'
        dockerImage = ''
    }
    
    stages {

    
    stage('Building image') {

        agent { 
          dockerfile {
            filename 'Dockerfile.prod'
            dir 'loginApp'
            additionalBuildArgs  '--platform=linux/amd64'
          }
      }
      
      steps {
           sh '''
            npm --version
          '''
      }
    }
    
    
    stage('Upload Image') {
     steps{    
         script {
            docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            }
        }
      }
    }
  }
}